src/Entity/TaskList.php
<?php

namespace App\Entity;

use App\Util\Format;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskListRepository")
 * @UniqueEntity("z_order", message="Cet ordre est déjà occupé par une autre liste."
 * )
 */
class TaskList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $z_order;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="task_list", orphanRemoval=true)
     * @ORM\OrderBy({"z_order" = "ASC", "created_at" = "DESC"})
     */
    private $tasks;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        // Valeurs par défaut
        $this->created_at = new \DateTime();
        $this->tasks = new ArrayCollection();
    }

    public function __toString()
    {
        return Format::mb_ucfirst($this->name);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getZOrder(): ?int
    {
        return $this->z_order;
    }

    public function setZOrder(?int $z_order): self
    {
        $this->z_order = $z_order;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        // Ordonnées par "z_order" et "created_at" de manière à avoir toujours les dernières tâches créées 
        // en premières positions pour un même z_order
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setTaskList($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->contains($task)) {
            $this->tasks->removeElement($task);
            // set the owning side to null (unless already changed)
            if ($task->getTaskList() === $this) {
                $task->setTaskList(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/TaskListType.php
<?php

namespace App\Form;

use App\Entity\TaskList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class TaskListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Intitulé (*)',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un intitulé.'
                    ]),
                    new Length([
                        'min' => 2,
                        'max' => 30,
                        'minMessage' => 'Libellé trop court. Minimum {{ limit }} caractères',
                        'maxMessage' => 'Libellé trop long. Maximum {{ limit }} caractères',
                    ]),
                ]
            ])
            ->add('z_order', IntegerType::class, [
                'label' => 'Ordre d\'affichage (*)',
                'help' => 'Minimum : 1. Maximum : 50.',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Ordre d\'affichage obligatoire.'
                    ]),
                    new Range([
                        'min' => 1,
                        'max' => 50,
                        'minMessage' => "L'ordre doit au moins être de {{ limit }}.",
                        'maxMessage' => "L'ordre ne doit pas être supérieur à {{ limit }}."
                    ])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TaskList::class,
        ]);
    }
}

src/Controller/TaskListController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Entity\TaskList;
use App\Form\TaskListType;
use App\Repository\TaskRepository;
use App\Repository\TaskListRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TaskListController extends AbstractController
{
    /**
     * Page centrale de l'application
     * 
     * @Route("/", name="home_page")
     */
    public function index(TaskListRepository $taskListRepository, TaskRepository $taskRepository, Request $request)
    {
        $lists = $taskListRepository->findBy([], [
            'z_order' => 'ASC'
        ]);

        return $this->render('list/index.html.twig', [
            'lists' => $lists
        ]);
    }

    /**
     * @Route("/lists", name="task_list_index", methods={"GET"})
     */
    public function getAll(TaskListRepository $taskListRepository): Response
    {
        return $this->render('task_list/index.html.twig', [
            'task_lists' => $taskListRepository->findBy([], [
                'z_order' => 'ASC'
            ]),
        ]);
    }

    /**
     * @Route("/list/add", name="task_list_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $taskList = new TaskList();
        $form = $this->createForm(TaskListType::class, $taskList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($taskList);
            $entityManager->flush();

            // Message Flash
            $this->addFlash(
                'success',
                'Liste créée.'
            );

            return $this->redirectToRoute('task_list_index');
        }

        return $this->render('task_list/new.html.twig', [
            'task_list' => $taskList,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/list/{id}/edit", name="task_list_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TaskList $taskList): Response
    {
        $form = $this->createForm(TaskListType::class, $taskList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            // Message Flash
            $this->addFlash(
                'success',
                'Liste modifiée.'
            );

            return $this->redirectToRoute('task_list_index');
        }

        return $this->render('task_list/edit.html.twig', [
            'task_list' => $taskList,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/list/{id}/delete", name="task_list_delete", methods={"GET"})
     */
    public function delete(TaskList $taskList, EntityManagerInterface $em): Response
    {
        // On supprime la liste
        // le "orphanRemoval" inscrit dans l'entité TaskList aura pour effet de supprimer les enfants isolés de la liste concernée
        $em->remove($taskList);
        $em->flush();

        // Message Flash
        $this->addFlash(
            'success',
            'Liste supprimée (avec toutes ses tâches associées).'
        );

        return $this->redirectToRoute('task_list_index');
    }
}

templates/task_list/_delete_modal.html.twig
<div class="modal fade" id="delete_list_{{ list.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalList" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-dark" id="exampleModalLabel">Suppression de la liste</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="text-dark p-3">
          <h3>Confirmez la suppression de la liste.</h3>
          <h5><i class="fas fa-arrow-right"></i> {{ list.name|capitalize }}</h5>
          <p class="text-danger">
            Attention ! En supprimant cette liste, toutes les tâches associées seront supprimées.<br>
            <b>Cette opération est irréversible.</b>
          </p>
        </div>

        <div class="modal-footer">
          <a href="{{ path('task_list_delete', {id: list.id}) }}" type="button" class="btn btn-danger">Confirmer</a>
          <button type="button" class="btn btn-primary" data-dismiss="modal">Annuler</button>
        </div>
      </div>
    </div>
  </div>

templates/task_list/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-info">Valider</button>
{{ form_end(form) }}

templates/task_list/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Liste{% endblock %}

{% block body %}
<div class="col-6 mx-auto">
    <h2 class="mt-3">Modification Liste</h2>

    <div class="bg-light text-dark my-3 p-3">
        {{ include('task_list/_form.html.twig') }}

        <a href="{{ path('task_list_index') }}" >Retour au Listing</a>        
    </div>
</div>

{% endblock %}

templates/task_list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listes{% endblock %}

{% block body %}
    <div class="col-10 mx-auto">
        <h2 class="mt-3">Listing</h2>
        <table class="table bg-light text-dark my-3">
            <thead>
                <tr>
                    <th>Libellé</th>
                    <th>Nb. tâches</th>
                    <th>Ordre d'affichage</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for task_list in task_lists %}
                <tr>
                    <td>{{ task_list.name|capitalize }}</td>
                    <td>{{ task_list.tasks|length }}</td>
                    <td>{{ task_list.zOrder }}</td>
                    <td>
                        <a href="{{ path('task_list_edit', {'id': task_list.id}) }}"><i class="fas fa-edit"></i> Modifier</a><br>
                        <a href="#" data-toggle="modal" data-target="#delete_list_{{ task_list.id }}"><i class="fas fa-trash-alt"></i> Supprimer</a>
                    </td>
                </tr>
            
            {# Création des modals de suppression #}
            {% include 'task_list/_delete_modal.html.twig' with {list: task_list} %}
    
            {% else %}
            {# Si aucune liste créée #}
                <tr>
                    <td colspan="5">Aucune liste créée</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{{ path('task_list_new') }}" class="btn btn-success">Créer une liste</a>
        <a href="{{ path('home_page') }}" class="btn btn-warning">Retour Trello</a>
    </div>
{% endblock %}

templates/task_list/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle liste{% endblock %}

{% block body %}
<div class="col-6 mx-auto">
    <h2 class="mt-3">Nouvelle liste</h2>

    <div class="bg-light text-dark my-3 p-3">

        {{ include('task_list/_form.html.twig') }}

        <a href="{{ path('task_list_index') }}">Retour au Listing</a>
    </div>
</div>
{% endblock %}