src/Entity/Task.php
<?php

namespace App\Entity;

use App\Util\Format;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $z_order;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TaskList", inversedBy="tasks")
     */
    private $task_list;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Priority", inversedBy="tasks")
     */
    private $priority;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        // Valeurs par défaut
        $this->created_at = new \DateTime();
    }

    public function __toString()
    {
        return Format::mb_ucfirst($this->name);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getZOrder(): ?int
    {
        return $this->z_order;
    }

    public function setZOrder(?int $z_order): self
    {
        $this->z_order = $z_order;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getTaskList(): ?TaskList
    {
        return $this->task_list;
    }

    public function setTaskList(?TaskList $task_list): self
    {
        $this->task_list = $task_list;

        return $this;
    }

    public function getPriority(): ?Priority
    {
        return $this->priority;
    }

    public function setPriority(?Priority $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/list/_modal.html.twig
<div class="modal fade" id="task{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-dark" id="exampleModalLabel">Mise à jour Tâche</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="alert alert-danger" role="alert" id="error_message_form_{{ id }}" style="display: none;">

        </div>

        <div class="modal-body text-dark">
          {% include 'task/_form.html.twig' with {form: form, id: id} %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        </div>
      </div>
    </div>
  </div>

templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ascanio - Trello{% endblock %}

{% block body %}
<div class="lists mt-3">
    {# Boucle des listes #}
    {% for indexList, list in lists %}
    <div class="list">
        <header class="d-flex justify-content-between align-items-center"><span class="badge badge-secondary">{{ list.name|capitalize }} ({{ list.tasks|length }})</span> <a href="{{ path('task_list_index') }}" class="btn btn-warning py-0 px-1" title="Gestion des listes"><i class="fas fa-cog"></i></a></header>
        <ul>
            {# Boucle des tâches #}
            {% for task in list.tasks %}
            <li>
                <div class="card">
                    <div class="card-body pb-2">
                        <h5 class="card-title"><b>{{ task.name|capitalize }}</b></h5>
                        <h6 class="card-subtitle mb-2 text-{{ task.priority.color }}"><span class="badge badge-pill badge-{{ task.priority.color }}">{{ task.zorder }}</span> - {{ task.priority.name|capitalize }}</h6>
                        <p class="card-text">{{ task.content|nl2br }}</p>
                        <div class="text-center p-0 pb-2">
                            {% if not loop.first %}
                                <a href="{{ path('task_up', {id: task.id}) }}" type="button" class="btn btn-dark text-light p-0 px-2" title="Déplacer en haut"><i class="fas fa-arrow-circle-up"></i></a>
                            {% endif %}
                            {% if not loop.last %}
                                <a href="{{ path('task_down', {id: task.id}) }}" type="button" class="btn btn-dark text-light p-0 px-2" title="Déplacer en bas"><i class="fas fa-arrow-circle-down"></i></a>
                            {% endif %}
                            {% if indexList != 0 %}
                                <a href="{{ path('task_left', {id: task.id}) }}" type="button" class="btn btn-dark text-light p-0 px-2" title="Déplacer à gauche"><i class="fas fa-arrow-circle-left"></i></a>
                            {% endif %}
                            {% if indexList != ((lists|length) - 1) %}
                                <a href="{{ path('task_right', {id: task.id}) }}" type="button" class="btn btn-dark text-light p-0 px-2" title="Déplacer à droite"><i class="fas fa-arrow-circle-right"></i></a>
                            {% endif %}
                        </div>
                        <div class="text-center">
                            <button type="button" class="btn btn-primary text-light p-0 px-2 mr-2 update_task_action" data-toggle="modal" data-target="#task" data-task-url="{{ path('task_edit', {id: task.id}) }}">Modifier</button>
                            <span type="button" data-toggle="modal" data-target="#delete_task" data-toggle="tooltip" data-placement="right" title="Supprimer" data-task-delete-url="{{ path('task_delete', {id: task.id}) }}" data-task-name="{{ task.name }}" data-task-list="{{ task.taskList.name }}" class="delete_task_action"><i class="fas fa-trash text-danger"></i></span>
                        </div>
                    </div>
                </div>
            </li>

            {% else %}
            {# Si aucune tâche créée #}
                <li>Aucune tâche créée.</li>
            {% endfor %}
        </ul>
        {# Gestion du bouton d'ajout d'une nouvelle tâche #}
        <footer class="text-dark">
            <button type="button" 
                class="btn btn-success text-light p-0 px-2 mr-2 add_task_action" 
                data-toggle="modal" 
                data-target="#task" 
                data-task-url="{{ path('task_new') }}"
                data-list-id="{{ list.id }}"> {# Ce dataset permettra de pré-sélectionner la liste d'appartenance dans le formulaire de création #}
                <i class="fas fa-plus-circle"></i> Ajouter
            </button>

        </footer>
    </div>
    {% else %}
    {# Si aucune liste créée #}
        <p>Aucune liste créée.<br><a href="{{ path('task_list_new') }}" class="text-light font-weight-bold"><i class="fas fa-plus-circle"></i> Créer une liste</a></p>
    {% endfor %}
</div>

{# Inclusion des modals
    le contenu est chargé dynamiquement #}
{% include 'task/_form_modal.html.twig' %}
{% include 'task/_delete_modal.html.twig' %}


{% endblock %}